steps:
  - uses: actions/checkout@master
  - uses: codecov/codecov-action@v3
    with:
      files: ./coverage/coverage-final.json
      flags: unittests
      fail_ci_if_error: true
      verbose: true
